image: docker:latest  # Use a Docker image that has Docker pre-installed

services:
  - docker:dind  # Docker-in-Docker service to run Docker commands

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - echo "Logging into GitLab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker --version  # Check Docker version to verify it's working
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/dayn08/mytestwebsite .
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push registry.gitlab.com/dayn08/mytestwebsite
  only:
    - main

deploy:
  stage: deploy
  before_script: 
    # Create the .ssh directory if it doesn't exist
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Add the SSH private key to the file and set permissions
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Disable strict host key checking to prevent host key verification issues
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
  script:
    # Stop and remove existing container, run the registry container
    - ssh ubuntu@54.251.195.21 "
      docker ps -q --filter 'ancestor=registry.gitlab.com/dayn08/mytestwebsite' | xargs -r docker stop && 
      docker ps -a -q --filter 'ancestor=registry.gitlab.com/dayn08/mytestwebsite' | xargs -r docker rm && 
      docker pull registry.gitlab.com/dayn08/mytestwebsite && 
      docker run -d -p 8080:80 registry.gitlab.com/dayn08/mytestwebsite"

  only:
    - main