image: docker:latest  # Use a Docker image that has Docker pre-installed

services:
  - docker:dind  # Docker-in-Docker service to run Docker commands

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - echo "Logging into GitLab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker --version  # Check Docker version to verify it's working
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/dayn08/mytestwebsite .
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push registry.gitlab.com/dayn08/mytestwebsite
  only:
    - main

test_ssh_connection:
  stage: test
  before_script: 
    # Create the .ssh directory if it doesn't exist
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Add the SSH private key to the file and set permissions
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@ec2-54-151-137-218.ap-southeast-1.compute.amazonaws.com "echo 'SSH connection successful!'"
  only:
    - main


deploy:
  stage: deploy
  before_script:
    # Create the .ssh directory if it doesn't exist
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Add the SSH private key to the file and set permissions
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@ec2-54-151-137-218.ap-southeast-1.compute.amazonaws.com "
      docker ps -q --filter 'ancestor=registry.gitlab.com/Dayn08/mytestwebsite' | xargs -r docker stop && 
      docker ps -a -q --filter 'ancestor=registry.gitlab.com/Dayn08/mytestwebsite' | xargs -r docker rm && 
      docker pull registry.gitlab.com/Dayn08/mytestwebsitet && 
      docker run -d -p 80:80 registry.gitlab.com/Dayn08/mytestwebsitet"

  only:
    - main