image: docker:latest  # Use a Docker image that has Docker pre-installed

services:
  - docker:dind  # Docker-in-Docker service to run Docker commands

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - cho "Logging into GitLab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker --version  # Check Docker version to verify it's working
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/frontendwebsite/daisoproject .
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push registry.gitlab.com/frontendwebsite/daisoproject
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Image pushed to registry successfully. Deployment step goes here."
  only:
    - main