image: docker:latest  # Use a Docker image that has Docker pre-installed

services:
  - docker:dind  # Docker-in-Docker service to run Docker commands

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - echo "Logging into GitLab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker --version  # Check Docker version to verify it's working
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/dayn08/mytestwebsite .
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push registry.gitlab.com/dayn08/mytestwebsite
  only:
    - main

deploy:
  stage: deploy
  script:
    # Stop and remove existing container, run the registry container
    - ssh "$SSH_PRIVATE_KEY" ubuntu@ec2-54-251-195-21.ap-southeast-1.compute.amazonaws.com "
      docker ps -q --filter 'ancestor=registry.gitlab.com/dayn08/mytestwebsite' | xargs -r docker stop && 
      docker ps -a -q --filter 'ancestor=registry.gitlab.com/dayn08/mytestwebsite' | xargs -r docker rm && 
      docker pull registry.gitlab.com/dayn08/mytestwebsite && 
      docker run -d -p 8080:80 registry.gitlab.com/dayn08/mytestwebsite"

  only:
    - main